export const BACKEND_API_ROADS = {
    BASE_URL: "http://localhost:8080/api",
    TYPES: "/types",
    USERS: "/users",
    PLAYERS: "/players",
    LOGIN: "/authentication",
    ACCESS_GRANTED: "/access",
    ALTERED: "/sync/altered",
    TOKEN: "/token",
    REFRESH: "/refresh"
};

export const BACKEND_API_TYPES = {
    ROOT: `${BACKEND_API_ROADS.BASE_URL}${BACKEND_API_ROADS.TYPES}`
};

export const BACKEND_API_ALTERED = {
    ROOT: `${BACKEND_API_ROADS.BASE_URL}${BACKEND_API_ROADS.ALTERED}`
};

export const BACKEND_API_USERS = {
    ROOT: `${BACKEND_API_ROADS.BASE_URL}${BACKEND_API_ROADS.USERS}`,
    LOGIN: `${BACKEND_API_ROADS.BASE_URL}${BACKEND_API_ROADS.USERS}${BACKEND_API_ROADS.LOGIN}`,
    ACCESS_GRANTED: `${BACKEND_API_ROADS.BASE_URL}${BACKEND_API_ROADS.USERS}${BACKEND_API_ROADS.ACCESS_GRANTED}`,
    REFRESH_TOKEN: `${BACKEND_API_ROADS.BASE_URL}${BACKEND_API_ROADS.USERS}${BACKEND_API_ROADS.TOKEN}${BACKEND_API_ROADS.REFRESH}`
}

export const BACKEND_API_PLAYERS = {
    ROOT: `${BACKEND_API_ROADS.BASE_URL}${BACKEND_API_ROADS.PLAYERS}`,
    BY_USER_ID: `${BACKEND_API_ROADS.BASE_URL}${BACKEND_API_ROADS.PLAYERS}${BACKEND_API_ROADS.USERS}`
}